{"name": "test_rerun", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_rerun():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_rerun.py:2: AssertionError"}, "start": 1631177330231, "stop": 1631177330231, "uuid": "239ca3fc-28da-4805-b399-cc032c83e9fd", "historyId": "60cfbff1ee1732942c6cc7573f29a8c5", "testCaseId": "7cd60c23380911745cbaab52c667c5dd", "fullName": "result.test_rerun#test_rerun", "labels": [{"name": "parentSuite", "value": "result"}, {"name": "suite", "value": "test_rerun"}, {"name": "host", "value": "DESKTOP-GRKQKVO"}, {"name": "thread", "value": "54832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "result.test_rerun"}]}